// api/webapp/i18n.js
window.I18N = {
  en: {
    catalog: "Catalog",
    language: "Language",
    city: "City",
    district: "District",
    type: "Type",
    maxPrice: "Max price (€)",
    reset: "Reset",
    show: "Show",
    listings: "Listings",
    any: "—",
    apartment: "Apartment",
    house: "House",
  },

  ru: {
    catalog: "Каталог",
    language: "Язык",
    city: "Город",
    district: "Район",
    type: "Тип",
    maxPrice: "Макс. цена (€)",
    reset: "Сброс",
    show: "Показать",
    listings: "Объявления",
    any: "—",
    apartment: "Квартира",
    house: "Дом",
  },

  bg: {
    catalog: "Каталог",
    language: "Език",
    city: "Град",
    district: "Квартал",
    type: "Тип",
    maxPrice: "Макс. цена (€)",
    reset: "Нулиране",
    show: "Покажи",
    listings: "Обяви",
    any: "—",
    apartment: "Апартамент",
    house: "Къща",
  },

  he: {
    catalog: "קטלוג",
    language: "שפה",
    city: "עיר",
    district: "אזור",
    type: "סוג",
    maxPrice: "מחיר מקס׳ (€)",
    reset: "איפוס",
    show: "הצג",
    listings: "מודעות",
    any: "—",
    apartment: "דירה",
    house: "בית",
  },
};
